drop table if exists auth_data cascade;
drop table if exists orders cascade;
create table auth_data (
        id bigint generated by default as identity,
        email varchar(255) not null unique,
        login varchar(255) not null unique,
        name varchar(255) not null,
        password varchar(255) not null,
        phone varchar(255) not null unique,
        role enum ('ADMIN','USER') not null,
        primary key (id)
);
create table orders (
        date timestamp(6) not null,
        id bigint generated by default as identity,
        user_id bigint not null,
        primary key (id)
);
alter table if exists orders 
       add constraint FK4qie9imb548b6lmjc278grlv0 
       foreign key (user_id) 
       references auth_data;